name: Java Tests

env:
  ALLURE: 2.29.0
  LANGUAGE: 'Java'

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - chromium
        - firefox

jobs:
  test_playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.44.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          java --version
          ./run.sh --lang "$LANGUAGE" --docker "playwright" --browser "${{ inputs.browser }}"
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_allure_playwright
          path: reporting/allure-results/java


  test_selenium:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/standalone-${{ inputs.browser }}
        ports: 
        - 4444:4444
        options: --shm-size=2gb
    container:
       image: maven:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          java --version
          ./run.sh --lang "$LANGUAGE" --docker "selenium" --browser "${{ inputs.browser }}" --hub "selenium-hub"
          #echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_allure_selenium
          path: reporting/allure-results/java


  test_karate:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/standalone-${{ inputs.browser }}
        ports: 
        - 4444:4444
        options: --shm-size=2gb
    container:
       image: maven:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          java --version
          ./run.sh --lang "$LANGUAGE" --docker "karate" --browser "${{ inputs.browser }}" --hub "selenium-hub"
          #echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
          mv tests-java/target/karate-reports reporting/report-karate
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_allure_karate
          path: reporting/allure-results/java
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_karate
          path: reporting/report-karate

  report:
    needs: [test_playwright, test_selenium, test_karate]
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Allure Playwright artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_playwright
          path: reporting/allure-results/java1
      - name: Download Allure Selenium artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_selenium
          path: reporting/allure-results/java2
      - name: Download Allure Karate artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_karate
          path: reporting/allure-results/java3
      - name: Download Karate artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_karate
          path: reporting/report-karate
      - name: Report
        run: |
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          ./allure.sh --lang $LANGUAGE --browser ${{ inputs.browser }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_report
          path: |
            reporting/allure-reports/report-java
            reporting/report-karate


  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_report
      - name: Commit
        run: |
          ls
          ls -R allure-reports
          rm -rf docs/*
          mv allure-reports/report-java docs/
          mv karate-report/* docs/
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit - Java tests"
          git push origin main
