name: Java Tests

env:
  LANGUAGE: 'Java'

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox

jobs:
  test_playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.44.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          cd tests-java
          # mvn -Dtest="web_playwright/WebFormTest, cucumber/petstore/**" test
          mvn -Dtest="web_playwright/**, petstore/**, cucumber/**" -Dbrowser=${{ inputs.browser }} test
          cd ..
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_playwright
          path: reporting/allure-results/java

  test_selenium:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-${{ inputs.browser }}
        ports: 
        - 4444:4444
        options: --shm-size=2gb
    container:
       image: maven:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          #ls /__w/demo/demo/tests-java/src/test/resources
          cd tests-java
          mvn -Dtest="web_selenium/**" -Dbrowser="${{ inputs.browser }}" -Dhub="172.17.0.1" test
          cd ..
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_selenium
          path: reporting/allure-results/java


  report:
    needs: [test_playwright, test_selenium]
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    env:
      ALLURE: 2.27.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Playwright artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_playwright
          path: reporting/allure-results/java1
      - name: Download Selenium artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_selenium
          path: reporting/allure-results/java2
      - name: Report
        run: |
          ls -R reporting/allure-results
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          ./allure.sh --lang $LANGUAGE --browser ${{ inputs.browser }}
          cat reporting/allure-results/java1/executor.json
          cat reporting/allure-results/java2/executor.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_report
          path: reporting/allure-reports/java/index.html

  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_report
      - name: Commit
        run: |
          rm -rf docs/*
          mv index.html docs/report-allure.html
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit - Java tests"
          git push origin main
