name: Node.js Cypress Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox
        - webkit

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          cd tests-nodejs
          npm install
          cd ..
      - name: Test
        run: |
          cd tests-nodejs
          npx cucumber-js cucumber/features/petstore.feature
          npx cypress run --browser ${{ inputs.browser }}
          cd ..
