name: Python Tests

env:
  LANGUAGE: 'Python'
  HUB: '172.17.0.1'

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox
        - webkit

jobs:
  test_playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install -r tests-python/requirements.txt
          playwright install
      - name: Test
        run: |
          ./run.sh --lang $LANGUAGE --docker playwright --browser ${{ inputs.browser }}
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/python/job.url
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_playwright
          path: reporting/allure-results/python


  test_selenium:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-${{ inputs.browser }}
        ports: 
        - 4444:4444
        options: --shm-size=2gb
    #container:
    #  image: python:v3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Test
        run: |
          #127.0.0.1curl http://${HUB}:4444/wd/hub/
          ./run.sh --lang $LANGUAGE --docker selenium --browser ${{ inputs.browser }}

  report:
    needs: [test_playwright]
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    env:
      ALLURE: 2.27.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_playwright
          path: reporting/allure-results/python1
      - name: Report
        run: |
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          ./allure.sh --lang $LANGUAGE --browser ${{ inputs.browser }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_report
          path: reporting/allure-reports/python/index.html

  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_report
      - name: Commit
        run: |
          rm -rf docs/*
          mv index.html docs/report-allure.html
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit - Python tests"
          git push origin main
