name: robotframework/playwright

env:
  ALLURE: 2.29.0

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: marketsquare/robotframework-browser
      options: --user pwuser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          ./docker.sh --browser "${{ inputs.browser }}" --docker robotframework/playwright
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting
  

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_test
          path: reporting
      - name: Commit
        run: |
          rm -rf docs/*
          mv reporting/report-* docs/
          #mv reporting/allure-reports/report-* docs/
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit"
          git push origin main
