name: Robot Framework Selenium Tests

env:
  ALLURE: 2.29.0
  LANGUAGE: 'Python'

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox

jobs:
  test_robotframework_selenium:
    runs-on: ubuntu-latest
    container:
      image: robotframework/rfdocker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install -r tests-python/requirements.txt
      - name: Test
        run: |
          cd tests-python
          robot web_robot_framework/tests/webform_page.robot
          cd ..
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_robotframework_selenium
          path: |
            tests-python/log.html
            tests-python/report.html
            



  report:
    needs: [test_robotframework_selenium]
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    steps:
      - name: Checkout
        uses: actions/checkout@v4robotframework_selenium
      - name: Report
        run: |
          exit
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          ./allure.sh --lang $LANGUAGE --browser ${{ inputs.browser }}

  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_robotframework_selenium
      - name: Commit
        run: |
          #rm -rf docs/report-python/
          mkdir docs/report-robotframework-selenium
          mv report.html docs/report-robotframework-selenium/
          mv log.html docs/report-robotframework-selenium/
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit - Robot Framework tests"
          git push origin main
