name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - all
        - chrome
        - firefox
        - edge

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install
        run: |
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          cd tests-java
          # mvn -Dtest="web_selenium/**" test
          cd ..
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting/
