name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - chrome
        - chromium
        - edge
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-${{ inputs.browser }}
        ports: 
        - "4444:4444"
        options: --shm-size=2gb
    container:
       image: maven:3-eclipse-temurin-17-focal
       #image: selenium/standalone-${{ inputs.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- uses: actions/setup-java@v3
        #with:
        #  distribution: 'oracle'
        #  java-version: '17'
      - name: Install
        run: |
          #which firefox
          #which google-chrome
          #apt-get update
          #apt-get install maven
          #chmod +x webdrivers/*
          #mv webdrivers/* /usr/local/bin/
          cd tests-java
          mvn dependency:resolve
          cd ..
      - name: Test
        run: |
          ls /__w/demo/demo/tests-java/src/test/resources
          cd tests-java
          mvn -Dtest="web_selenium/WebFormTest" -Dbrowser="${{ inputs.browser }}" test
          #-Dwebdriver.chrome.driver="webdrivers/chromedriver" \
          #-Dwebdriver.edge.driver="webdrivers/msedgedriver" \
          #-Dwebdriver.firefox.driver="webdrivers/geckodriver" \
          #test
          cd ..
        #env:
        #  HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting/

  report:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    env:
      ALLURE: 2.27.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_test
      - name: Report
        run: |
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          allure generate \
            --clean \
            --output allure-report \
            --single-file \
            allure-results/java-results
          ls
          ls allure-report
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_report
          path: allure-report/index.html

  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_report
      - name: Commit
        run: |
          rm -rf docs/*
          mv index.html docs/report-selenium.html
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add docs/*
          git commit -m "Github Commit - Selenium tests"
          git push origin main
