name: Tests

env:
  ALLURE: 2.29.0
  LANGUAGE: "All"

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - Firefox
        - Chrome
        - Chromium
        - Edge

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: harmin/qa-runner:0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          rm -rf reporting/*
          mkdir /tmp/test
          #cp tests-python/file.xml /tmp/test/
          pip3 install --break-system-package -r tests-python/requirements.txt
          playwright install
          mvn -f tests-java/pom.xml dependency:resolve
          cd tests-nodejs
          npm install
          cd ..
          npx playwright install
      - name: Test
        run: |
          java --version
          python3 --version
          nodejs --version
          npm --version
          whoami
          echo $HOME
          ./run.sh --lang "$LANGUAGE" --docker "playwright" --browser "${{ inputs.browser }}"
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_allure_playwright
          path: |
            reporting/allure-results/java
            reporting/allure-results/python
            reporting/allure-results/nodejs
            reporting/report-karate
            reporting/report-playwright
            reporting/report-pytest
            reporting/report-robot/


  report:
    needs: tests
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jre
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Allure Playwright artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_playwright
          path: reporting/allure-results/java1
      - name: Download Allure Selenium artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_allure_selenium
          path: reporting/allure-results/java2
      #- name: Download Allure Karate artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: artifact_allure_karate
      #    path: reporting/allure-results/java3
      #- name: Download Karate artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: artifact_karate
      #    path: reporting/report-karate
      - name: Report
        run: |
          curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.zip -L -o /tmp/allure.zip
          unzip /tmp/allure.zip -d /usr/local/
          ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
          ./allure.sh --lang $LANGUAGE --browser ${{ inputs.browser }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_report
          path: |
            reporting/allure-reports/report-java
            reporting/allure-reports/report-python
            reporting/allure-reports/report-nodejs
            reporting/report-karate
            reporting/report-playwright
            reporting/report-pytest
            reporting/report-robot/

  publish:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_report
          path: report-java/
      - name: Commit
        run: |
          rm -rf docs/*
          #mkdir docs/report-java
          mv index.html docs/
          #mv allure-reports/report-java docs/
          #mv report-karate/* docs/
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add -f docs/*
          git commit -m "Github Commit - Java tests"
          git push origin main
